# Generated by Django 4.2.6 on 2023-10-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_todo_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
