# Generated by Django 4.2.6 on 2023-10-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_todo_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
